#!/bin/bash
echo 'never' > /sys/kernel/mm/transparent_hugepage/enabled
echo 'never' > /sys/kernel/mm/transparent_hugepage/defrag
`systemctl daemon-reload`
`systemctl start disable-thp`
`systemctl enable disable-thp`

